### ISSUE TITLE
Version 14.0.0 published on npmjs has exact version peer dependency "@angular/platform-browser-dynamic"

### ISSUE THREAD

**Issue by grubeninspekteur** [ngxp/store-service#59]
The published version has a hard dependency on `"@angular/platform-browser-dynamic": "14.2.5"`. The published code seems not to be the same as in the repo.

**Comment by joostme** [comment]
Thanks for the feedback. It seems like either NX or ng-packagr automatically adds `@angular/platform-browser-dynamic` to the peerDependencies if it's missing. And it's using the root package.json version for that.
I explicitly set it to `^14.0.0` to fix the issue.

The new version `v14.0.1` fixed this.
