### ISSUE TITLE
RxJs 7 support

### ISSUE THREAD

**Issue by grubeninspekteur** [ngxp/store-service#60]
The library seems to work fine with RxJs 7. If it does not use any deprecated API, please consider adding RxJs 7 to the allowed versions in the peer dependencies using "||" semver syntax.

**Comment by joostme** [comment]
I ran the sample application and the test with RxJS 7 and it worked fine. I added `^7.0.0` to the peerDependencies.

The new version `v14.0.1` now supports RxJS 7.
